# Generated by Django 5.2 on 2025-04-04 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('narodnost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.IntegerField(unique=True)),
                ('typ_pokoje', models.CharField(choices=[('jednoluzkovy', 'Jednolůžkový'), ('dvouluzkovy', 'Dvoulůžkový'), ('apartma', 'Apartmá')], max_length=20)),
                ('stav', models.CharField(choices=[('volny', 'Volný'), ('obsazeny', 'Obsazený')], max_length=20)),
                ('cena_za_noc', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kapacita', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_prijezdu', models.DateField()),
                ('datum_odjezdu', models.DateField()),
                ('pocet_osob', models.PositiveIntegerField()),
                ('stav', models.CharField(choices=[('potvrzeno', 'Potvrzeno'), ('ceka_na_potvrzeni', 'Čeká na potvrzení'), ('zruseno', 'Zrušeno')], max_length=30)),
                ('specialni_pozadavky', models.TextField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepce.host')),
                ('pokoj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepce.pokoj')),
            ],
        ),
        migrations.CreateModel(
            name='Platba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zpusob', models.CharField(choices=[('hotove', 'Hotově'), ('kartou', 'Kartou'), ('prevodem', 'Převodem')], max_length=20)),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum_platby', models.DateField(blank=True, null=True)),
                ('stav', models.CharField(choices=[('zaplaceno', 'Zaplaceno'), ('ceka_na_uhradu', 'Čeká na úhradu'), ('nezaplaceno', 'Nezaplaceno')], max_length=30)),
                ('rezervace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepce.rezervace')),
            ],
        ),
    ]
